"""TianGong L5 plugin host phase 1 package.

Only data-only shells, deterministic serialization helpers, readiness views,
invariant views, and guarantee records are exported here. Importing this package
must not discover plugins, load plugin code, touch L4 adapters, write registry
state, create sandboxes, or read credential material.
"""

from __future__ import annotations

from .audit_declaration import PluginAuditDeclaration
from .capability_token_declaration import PluginCapabilityTokenDeclaration
from .compatibility_declaration import PluginCompatibilityDeclaration
from .credential_declaration import PluginCredentialDeclaration
from .data_governance_declaration import PluginDataGovernanceDeclaration
from .entry_reference import PluginEntryReference
from .hot_switch_declaration import PluginHotSwitchDeclaration
from .manifest_hash import (
    PluginManifestDigest,
    PluginManifestHash,
    build_manifest_hash,
    calculate_manifest_digest,
    canonical_manifest_payload,
)
from .manifest_quality_gate import PluginManifestQualityGate
from .manifest_schema import PHASE2_REQUIRED_MANIFEST_FIELDS, PluginManifestSchema
from .manifest_validation import PluginManifestValidationIssue, PluginManifestValidationReport
from .mount_surface_declaration import PluginMountSurfaceDeclaration
from .permission_declaration import PluginPermissionDeclaration
from .resource_declaration import PluginResourceDeclaration
from .rollback_declaration import PluginRollbackDeclaration
from .signature_reference import PluginSignatureReference
from .source_trust import PluginSourceTrustReference
from .trust_boundary_declaration import PluginTrustBoundaryDeclaration
from .version_declaration import PluginVersionDeclaration


from .lifecycle_declaration import (
    PluginLifecycleStateRef,
    PluginLifecycleStateMachine,
    PluginLifecycleStatusKind,
    PluginLifecycleTransitionRule,
    PluginMountDeclaration,
    PluginMountSurfaceRef,
    has_forbidden_method,
    is_allowed_transition,
    is_live_entry_text,
    is_runtime_status_text,
    lifecycle_declaration_digest,
)
from .lifecycle_validation import (
    PluginLifecycleQualityGate,
    PluginLifecycleQualityGateDecision,
    PluginLifecycleValidationReport,
    PluginLifecycleValidator,
    PluginMountDeclarationConflictReport,
)
from .lifecycle_projection import (
    PluginLifecycleProjectionSummary,
    PluginLifecyclePublicProjection,
    PluginLifecyclePublicProjectionBuilder,
    projection_text_is_safe,
)
from .lifecycle_audit_index import (
    PluginLifecycleAuditEventRef,
    PluginLifecycleAuditIndex,
    PluginLifecycleAuditIndexBuilder,
)
from .self_healing_declaration import (
    PluginRecoveryPlanDeclaration,
    PluginSelfHealingDeclaration,
    PluginSelfHealingQualityGateDecision,
    PluginSelfHealingValidationReport,
    PluginSelfHealingValidator,
)

from .phase3_evidence import (
    L5Phase3RegressionEvidenceIndex,
    L5Phase3TestEvidenceIndex,
    L5Phase3TestEvidenceRecord,
)
from .registry_audit_index import PluginRegistryAuditEventRef, PluginRegistryAuditIndex
from .registry_conflict import (
    PluginRegistryConflict,
    PluginRegistryConflictKind,
    PluginRegistryConflictReport,
    PluginRegistryConflictSeverity,
)
from .registry_conflict_rules import PluginRegistryConflictRuleSet
from .registry_delta import PluginRegistryDelta, PluginRegistryDeltaItem, build_registry_delta
from .registry_index import PluginRegistryIndex
from .registry_key import PluginRegistryKey
from .registry_namespace import PluginRegistryNamespace
from .registry_projection import (
    PluginRegistryCredentialSummary,
    PluginRegistryProjectionSummary,
    PluginRegistryPublicProjection,
    public_projection_from_record,
)
from .registry_quality_gate import (
    L5Phase3QualityGateDecision,
    PluginRegistryQualityGate,
    PluginRegistryQualityGateResult,
)
from .registry_record import PluginRegistryRecord
from .registry_revision import PluginRegistryRevision
from .registry_scope import PluginRegistryScope
from .registry_serialization import (
    PluginRegistrySerializationDigest,
    registry_canonical_digest,
    registry_canonical_payload,
    registry_sort_key,
)
from .registry_validator import PluginRegistryValidator

from .audit_anchor import (
    PluginHostAccountabilityRef,
    PluginHostAuditAnchor,
    PluginHostEvidenceRef,
    PluginHostProvenanceRef,
    PluginHostTamperEvidenceRef,
)
from .boundary_baseline import PluginHostBoundaryBaseline
from .context import PluginHostContext
from .edit_scope import L5Phase1EditablePathScope, L5Phase1HashManifestRecord
from .error import L5PluginHostError
from .handoff_index import PluginHandoffEvidenceIndex, PluginHandoffEvidenceRecord
from .identity import PluginHostIdentity
from .invariants import L5Phase1InvariantSuite, L5Phase2InvariantSuite, L5Phase3InvariantSuite, L5Phase4InvariantSuite, L5Phase6InvariantSuite
from .manifest_view import PluginManifestView
from .no_l6_implementation_guarantee import L5NoL6ImplementationGuarantee
from .no_legacy_runtime_guarantee import L5NoLegacyRuntimeGuarantee
from .no_live_external_action_guarantee import L5NoLiveExternalActionGuarantee
from .no_lower_layer_mutation_guarantee import L5NoLowerLayerMutationGuarantee
from .package_descriptor import PluginPackageDescriptor
from .public_export_map import L5PublicExportMap
from .quality_gate import (
    L5Phase1BlockingFinding,
    L5Phase1NonBlockingFinding,
    L5Phase1QualityGateDecision,
    L5Phase1QualityGateSummary,
)
from .readiness import L5Phase1Readiness, PluginHostReadinessSummary, evaluate_phase1_responsibility_fields
from .registry_entry import PluginRegistryDataOnlyResult, PluginRegistryEntry
from .registry_snapshot import PluginRegistrySnapshot
from .result import L5PluginHostResult
from .serialization import to_l5_digest, to_l5_json, to_l5_primitive

from .phase5_boundary import (
    PHASE5_PHASE,
    PluginCapabilityTokenBoundaryDeclaration,
    PluginCredentialRequirementDeclaration,
    PluginDataGovernanceDeclaration as PluginPhase5DataGovernanceDeclaration,
    PluginDependencyDeclaration,
    PluginDependencyGraphSnapshot,
    PluginIsolationDeclaration,
    PluginPhase5AuditIndex,
    PluginPhase5AuditIndexBuilder,
    PluginPhase5BoundaryValidationReport,
    PluginPhase5BoundaryValidator,
    PluginPhase5Conflict,
    PluginPhase5ConflictKind,
    PluginPhase5ConflictSeverity,
    PluginPhase5PublicProjection,
    PluginPhase5PublicProjectionBuilder,
    PluginPhase5QualityGate,
    PluginPhase5QualityGateDecision,
    PluginPhase5SwitchBoundaryDeclaration,
    PluginResourceBoundaryDeclaration,
    PluginTrustBoundaryDeclaration as PluginPhase5TrustBoundaryDeclaration,
    has_forbidden_phase5_field_name,
    has_forbidden_phase5_method,
    has_live_locator,
    has_unbounded_resource_text,
    public_text_is_safe,
)


from .phase6_health import (
    PHASE6_PHASE,
    PluginHealthSignalDeclaration,
    PluginHealthCheckDeclaration,
    PluginHealthAssessmentReport,
    PluginIsolationDispositionDeclaration,
    PluginRecoveryPermissionPreconditionDeclaration,
    PluginHotSwitchPermissionPreconditionDeclaration,
    PluginRollbackPermissionPreconditionDeclaration,
    PluginReplayPermissionPreconditionDeclaration,
    PluginPhase6Conflict,
    PluginPhase6ConflictKind,
    PluginPhase6ConflictSeverity,
    PluginHealthValidator,
    PluginIsolationDispositionValidator,
    PluginRecoveryPermissionValidator,
    PluginHotSwitchPermissionValidator,
    PluginRollbackPermissionValidator,
    PluginReplayPermissionValidator,
    PluginPhase6QualityGate,
    PluginPhase6QualityGateDecision,
    PluginPhase6PublicProjection,
    PluginPhase6ProjectionBuilder,
    PluginPhase6AuditIndex,
    PluginPhase6AuditIndexBuilder,
    has_forbidden_phase6_field_name,
    has_forbidden_phase6_method,
    has_live_health_or_permission_locator,
    phase6_declaration_digest,
    phase6_public_text_is_safe,
)


from .affective_plugin_declaration import (
    AFFECTIVE_PLUGIN_KIND_REF,
    AFFECTIVE_MOUNT_KIND_REF,
    AFFECTIVE_CAPABILITY_KIND_REFS,
    AFFECTIVE_ALLOWED_MODULATION_REFS,
    AFFECTIVE_FORBIDDEN_MISUSE_REFS,
    AffectiveCapabilityDeclaration,
    AffectivePluginMountDeclaration,
    AffectiveModulationContractBinding,
    AffectiveSafetyBoundaryRef,
    AffectiveAuditBinding,
    AffectivePublicProjectionSummary,
    AffectiveL6HandoffRef,
    affective_declaration_digest,
    has_affective_live_locator,
    has_forbidden_affective_field_name,
)

from .phase7_boundary_gate import (
    PHASE7_PHASE,
    GENERIC_HOST_PASS,
    GENERIC_HOST_PASS_WITH_COMPATIBLE_EXTENSION,
    GENERIC_HOST_BLOCK_TOOL_ONLY,
    L5Phase7InvariantSuite,
    PluginGenericHostPrecheckReport,
    PluginGenericHostPrecheckValidator,
    PluginHostBoundaryGateDeclaration,
    PluginL3HandoffDeclaration,
    PluginL4AdapterHandoffDeclaration,
    PluginL6EntryDeclaration,
    PluginRouteDeclaration,
    PluginHookDeclaration,
    PluginEventSubscriptionDeclaration,
    PluginContractBindingDeclaration,
    PluginServiceMountBindingDeclaration,
    PluginCapabilityMountBindingDeclaration,
    PluginArtifactProductionMountBindingDeclaration,
    AffectivePluginMountDeclaration as Phase7AffectivePluginMountDeclaration,
    PluginHostGovernanceGateDeclaration,
    PluginPhase7Conflict,
    PluginPhase7ConflictKind,
    PluginPhase7ConflictSeverity,
    PluginPhase7ValidationReport,
    PluginHostBoundaryGateValidator,
    PluginCrossLayerHandoffValidator,
    PluginL3HandoffValidator,
    PluginL4AdapterHandoffValidator,
    PluginL6EntryValidator,
    PluginRouteValidator,
    PluginHookValidator,
    PluginEventSubscriptionValidator,
    PluginContractBindingValidator,
    PluginServiceMountBindingValidator,
    PluginCapabilityMountBindingValidator,
    PluginArtifactProductionMountValidator,
    PluginAffectiveMountValidator,
    PluginHostGovernanceGateValidator,
    PluginPhase7QualityGate,
    PluginPhase7QualityGateDecision,
    PluginPhase7PublicProjection,
    PluginPhase7ProjectionBuilder,
    PluginPhase7AuditIndex,
    PluginPhase7AuditIndexBuilder,
    has_forbidden_phase7_field_name,
    has_forbidden_phase7_method,
    has_live_phase7_locator,
    phase7_declaration_digest,
    phase7_public_text_is_safe,
)

from .test_evidence import (
    L5Phase1RegressionBaselineRecord,
    L5Phase1RegressionEvidenceIndex,
    L5Phase1TestEvidenceIndex,
    L5Phase1TestEvidenceRecord,
)

from .model_capability_invariants import (
    L5_MODEL_CAPABILITY_SCHEMA_VERSION,
    ModelProviderPermitScope,
    ModelInvocationBudgetPermitRef,
    ModelInvocationAuditRequirementRef,
    ModelInvocationCredentialHandleRef,
    ModelInvocationPermit,
    PluginModelAccessPolicy,
    ModelCredentialHandleOnlyPolicy,
    ModelBudgetRequiredPolicy,
    ModelAuditRequiredPolicy,
    ModelContextPolicyRequired,
    ModelProviderAllowlistPolicy,
    ModelProviderScopePolicy,
    PluginModelCapabilityRequirementOnlyInvariant,
    NoPluginRawModelSDKInvariant,
    NoPluginRawHTTPModelCallInvariant,
    scan_plugin_source_for_raw_model_access,
    build_plugin_model_access_invariants,
)

__all__ = (
    "L5NoL6ImplementationGuarantee",
    "L5NoLegacyRuntimeGuarantee",
    "L5NoLiveExternalActionGuarantee",
    "L5NoLowerLayerMutationGuarantee",
    "L5Phase1BlockingFinding",
    "L5Phase1EditablePathScope",
    "L5Phase1HashManifestRecord",
    "L5Phase1InvariantSuite",
    "L5Phase1NonBlockingFinding",
    "L5Phase1QualityGateDecision",
    "L5Phase1QualityGateSummary",
    "L5Phase1Readiness",
    "L5Phase1RegressionBaselineRecord",
    "L5Phase1RegressionEvidenceIndex",
    "L5Phase1TestEvidenceIndex",
    "L5Phase1TestEvidenceRecord",
    "L5PluginHostError",
    "L5PluginHostResult",
    "L5PublicExportMap",
    "PluginHandoffEvidenceIndex",
    "PluginHandoffEvidenceRecord",
    "PluginHostAccountabilityRef",
    "PluginHostAuditAnchor",
    "PluginHostBoundaryBaseline",
    "PluginHostContext",
    "PluginHostEvidenceRef",
    "PluginHostIdentity",
    "PluginHostProvenanceRef",
    "PluginHostReadinessSummary",
    "PluginHostTamperEvidenceRef",
    "PluginManifestView",
    "L5_MODEL_CAPABILITY_SCHEMA_VERSION",
    "ModelProviderPermitScope",
    "ModelInvocationBudgetPermitRef",
    "ModelInvocationAuditRequirementRef",
    "ModelInvocationCredentialHandleRef",
    "ModelInvocationPermit",
    "PluginModelAccessPolicy",
    "ModelCredentialHandleOnlyPolicy",
    "ModelBudgetRequiredPolicy",
    "ModelAuditRequiredPolicy",
    "ModelContextPolicyRequired",
    "ModelProviderAllowlistPolicy",
    "ModelProviderScopePolicy",
    "PluginModelCapabilityRequirementOnlyInvariant",
    "NoPluginRawModelSDKInvariant",
    "NoPluginRawHTTPModelCallInvariant",
    "scan_plugin_source_for_raw_model_access",
    "build_plugin_model_access_invariants",
    "PluginPackageDescriptor",
    "PluginRegistryDataOnlyResult",
    "PluginRegistryEntry",
    "PluginRegistrySnapshot",
    "evaluate_phase1_responsibility_fields",
    "to_l5_digest",
    "to_l5_json",
    "L5Phase2InvariantSuite",
    "PHASE2_REQUIRED_MANIFEST_FIELDS",
    "PluginAuditDeclaration",
    "PluginCapabilityTokenDeclaration",
    "PluginCompatibilityDeclaration",
    "PluginCredentialDeclaration",
    "PluginDataGovernanceDeclaration",
    "PluginEntryReference",
    "PluginHotSwitchDeclaration",
    "PluginManifestDigest",
    "PluginManifestHash",
    "PluginManifestQualityGate",
    "PluginManifestSchema",
    "PluginManifestValidationIssue",
    "PluginManifestValidationReport",
    "PluginMountSurfaceDeclaration",
    "PluginPermissionDeclaration",
    "PluginResourceDeclaration",
    "PluginRollbackDeclaration",
    "PluginSignatureReference",
    "PluginSourceTrustReference",
    "PluginTrustBoundaryDeclaration",
    "PluginVersionDeclaration",
    "build_manifest_hash",
    "calculate_manifest_digest",
    "canonical_manifest_payload",
    "L5Phase3InvariantSuite",
    "L5Phase3QualityGateDecision",
    "L5Phase3RegressionEvidenceIndex",
    "L5Phase3TestEvidenceIndex",
    "L5Phase3TestEvidenceRecord",
    "PluginRegistryAuditEventRef",
    "PluginRegistryAuditIndex",
    "PluginRegistryConflict",
    "PluginRegistryConflictKind",
    "PluginRegistryConflictReport",
    "PluginRegistryConflictRuleSet",
    "PluginRegistryConflictSeverity",
    "PluginRegistryCredentialSummary",
    "PluginRegistryDelta",
    "PluginRegistryDeltaItem",
    "PluginRegistryIndex",
    "PluginRegistryKey",
    "PluginRegistryNamespace",
    "PluginRegistryProjectionSummary",
    "PluginRegistryPublicProjection",
    "PluginRegistryQualityGate",
    "PluginRegistryQualityGateResult",
    "PluginRegistryRecord",
    "PluginRegistryRevision",
    "PluginRegistryScope",
    "PluginRegistrySerializationDigest",
    "PluginRegistryValidator",
    "build_registry_delta",
    "public_projection_from_record",
    "registry_canonical_digest",
    "registry_canonical_payload",
    "registry_sort_key",
    "L5Phase4InvariantSuite",
    "L5Phase6InvariantSuite",
    "PluginLifecycleAuditEventRef",
    "PluginLifecycleAuditIndex",
    "PluginLifecycleAuditIndexBuilder",
    "PluginLifecycleProjectionSummary",
    "PluginLifecyclePublicProjection",
    "PluginLifecyclePublicProjectionBuilder",
    "PluginLifecycleQualityGate",
    "PluginLifecycleQualityGateDecision",
    "PluginLifecycleStateRef",
    "PluginLifecycleStateMachine",
    "PluginLifecycleStatusKind",
    "PluginLifecycleTransitionRule",
    "PluginLifecycleValidationReport",
    "PluginLifecycleValidator",
    "PluginMountDeclaration",
    "PluginMountDeclarationConflictReport",
    "PluginMountSurfaceRef",
    "PluginRecoveryPlanDeclaration",
    "PluginSelfHealingDeclaration",
    "PluginSelfHealingQualityGateDecision",
    "PluginSelfHealingValidationReport",
    "PluginSelfHealingValidator",
    "has_forbidden_method",
    "is_allowed_transition",
    "is_live_entry_text",
    "is_runtime_status_text",
    "lifecycle_declaration_digest",
    "projection_text_is_safe",
    "PHASE5_PHASE",
    "PluginCapabilityTokenBoundaryDeclaration",
    "PluginCredentialRequirementDeclaration",
    "PluginPhase5DataGovernanceDeclaration",
    "PluginDependencyDeclaration",
    "PluginDependencyGraphSnapshot",
    "PluginIsolationDeclaration",
    "PluginPhase5AuditIndex",
    "PluginPhase5AuditIndexBuilder",
    "PluginPhase5BoundaryValidationReport",
    "PluginPhase5BoundaryValidator",
    "PluginPhase5Conflict",
    "PluginPhase5ConflictKind",
    "PluginPhase5ConflictSeverity",
    "PluginPhase5PublicProjection",
    "PluginPhase5PublicProjectionBuilder",
    "PluginPhase5QualityGate",
    "PluginPhase5QualityGateDecision",
    "PluginPhase5SwitchBoundaryDeclaration",
    "PluginResourceBoundaryDeclaration",
    "PluginPhase5TrustBoundaryDeclaration",
    "has_forbidden_phase5_field_name",
    "has_forbidden_phase5_method",
    "has_live_locator",
    "has_unbounded_resource_text",
    "public_text_is_safe",

    "PHASE6_PHASE",
    "PluginHealthSignalDeclaration",
    "PluginHealthCheckDeclaration",
    "PluginHealthAssessmentReport",
    "PluginIsolationDispositionDeclaration",
    "PluginRecoveryPermissionPreconditionDeclaration",
    "PluginHotSwitchPermissionPreconditionDeclaration",
    "PluginRollbackPermissionPreconditionDeclaration",
    "PluginReplayPermissionPreconditionDeclaration",
    "PluginPhase6Conflict",
    "PluginPhase6ConflictKind",
    "PluginPhase6ConflictSeverity",
    "PluginHealthValidator",
    "PluginIsolationDispositionValidator",
    "PluginRecoveryPermissionValidator",
    "PluginHotSwitchPermissionValidator",
    "PluginRollbackPermissionValidator",
    "PluginReplayPermissionValidator",
    "PluginPhase6QualityGate",
    "PluginPhase6QualityGateDecision",
    "PluginPhase6PublicProjection",
    "PluginPhase6ProjectionBuilder",
    "PluginPhase6AuditIndex",
    "PluginPhase6AuditIndexBuilder",
    "has_forbidden_phase6_field_name",
    "has_forbidden_phase6_method",
    "has_live_health_or_permission_locator",
    "phase6_declaration_digest",
    "phase6_public_text_is_safe",
    "to_l5_primitive",
    "AFFECTIVE_PLUGIN_KIND_REF",
    "AFFECTIVE_MOUNT_KIND_REF",
    "AFFECTIVE_CAPABILITY_KIND_REFS",
    "AFFECTIVE_ALLOWED_MODULATION_REFS",
    "AFFECTIVE_FORBIDDEN_MISUSE_REFS",
    "AffectiveCapabilityDeclaration",
    "AffectivePluginMountDeclaration",
    "AffectiveModulationContractBinding",
    "AffectiveSafetyBoundaryRef",
    "AffectiveAuditBinding",
    "AffectivePublicProjectionSummary",
    "AffectiveL6HandoffRef",
    "affective_declaration_digest",
    "has_affective_live_locator",
    "has_forbidden_affective_field_name",
    "PHASE7_PHASE",
    "GENERIC_HOST_PASS",
    "GENERIC_HOST_PASS_WITH_COMPATIBLE_EXTENSION",
    "GENERIC_HOST_BLOCK_TOOL_ONLY",
    "L5Phase7InvariantSuite",
    "PluginGenericHostPrecheckReport",
    "PluginGenericHostPrecheckValidator",
    "PluginHostBoundaryGateDeclaration",
    "PluginL3HandoffDeclaration",
    "PluginL4AdapterHandoffDeclaration",
    "PluginL6EntryDeclaration",
    "PluginRouteDeclaration",
    "PluginHookDeclaration",
    "PluginEventSubscriptionDeclaration",
    "PluginContractBindingDeclaration",
    "PluginServiceMountBindingDeclaration",
    "PluginCapabilityMountBindingDeclaration",
    "PluginArtifactProductionMountBindingDeclaration",
    "Phase7AffectivePluginMountDeclaration",
    "PluginHostGovernanceGateDeclaration",
    "PluginPhase7Conflict",
    "PluginPhase7ConflictKind",
    "PluginPhase7ConflictSeverity",
    "PluginPhase7ValidationReport",
    "PluginHostBoundaryGateValidator",
    "PluginCrossLayerHandoffValidator",
    "PluginL3HandoffValidator",
    "PluginL4AdapterHandoffValidator",
    "PluginL6EntryValidator",
    "PluginRouteValidator",
    "PluginHookValidator",
    "PluginEventSubscriptionValidator",
    "PluginContractBindingValidator",
    "PluginServiceMountBindingValidator",
    "PluginCapabilityMountBindingValidator",
    "PluginArtifactProductionMountValidator",
    "PluginAffectiveMountValidator",
    "PluginHostGovernanceGateValidator",
    "PluginPhase7QualityGate",
    "PluginPhase7QualityGateDecision",
    "PluginPhase7PublicProjection",
    "PluginPhase7ProjectionBuilder",
    "PluginPhase7AuditIndex",
    "PluginPhase7AuditIndexBuilder",
    "has_forbidden_phase7_field_name",
    "has_forbidden_phase7_method",
    "has_live_phase7_locator",
    "phase7_declaration_digest",
    "phase7_public_text_is_safe",
)

from .phase8_closure import (
    PHASE8_PHASE,
    L5_FINAL_PHASE,
    L5FinalConflictSeverity,
    L5FinalConflictKind,
    L5ClosureSummary,
    L5FreezeManifest,
    L5FinalPublicProjection,
    L5L6HandoffFreeze,
    L5GovernanceCoverageMatrix,
    L5CapabilityReadinessMatrix,
    L5FinalQualityGateDecision,
    L5FinalAuditIndex,
    L5FinalInvariantSuite,
    L5ClosureValidator,
    L5FreezeManifestValidator,
    L5FinalPublicProjectionBuilder,
    L5L6HandoffFreezeValidator,
    L5GovernanceCoverageMatrixValidator,
    L5CapabilityReadinessMatrixValidator,
    L5FinalQualityGate,
    L5FinalAuditIndexBuilder,
    phase8_declaration_digest,
    has_forbidden_phase8_method,
    has_forbidden_phase8_field_name,
    has_live_phase8_locator,
    phase8_public_text_is_safe,
)

__all__ += (
    "PHASE8_PHASE",
    "L5_FINAL_PHASE",
    "L5FinalConflictSeverity",
    "L5FinalConflictKind",
    "L5ClosureSummary",
    "L5FreezeManifest",
    "L5FinalPublicProjection",
    "L5L6HandoffFreeze",
    "L5GovernanceCoverageMatrix",
    "L5CapabilityReadinessMatrix",
    "L5FinalQualityGateDecision",
    "L5FinalAuditIndex",
    "L5FinalInvariantSuite",
    "L5ClosureValidator",
    "L5FreezeManifestValidator",
    "L5FinalPublicProjectionBuilder",
    "L5L6HandoffFreezeValidator",
    "L5GovernanceCoverageMatrixValidator",
    "L5CapabilityReadinessMatrixValidator",
    "L5FinalQualityGate",
    "L5FinalAuditIndexBuilder",
    "phase8_declaration_digest",
    "has_forbidden_phase8_method",
    "has_forbidden_phase8_field_name",
    "has_live_phase8_locator",
    "phase8_public_text_is_safe",
)
