"""L6 public plugin foundation common contracts.

Exports immutable, data-only contract objects for L6 public plugin development.
No object in this package loads plugins, calls models, calls tools, writes state,
reads credentials, allocates budgets, writes audit records, or bypasses L3/L4/L5.
"""

from __future__ import annotations

from .admission import (
    L6ContractPatchAuditIndex,
    L6ContractPatchPublicProjection,
    L6ContractPatchQualityGateDecision,
    L6MiniSpecialtyDesignEnvelope,
    L6PluginAdmissionDecision,
    L6PluginAdmissionKind,
    L6PluginAdmissionReport,
    L6PublicContractPatchImpactAssessment,
    L6PublicContractPatchProposal,
)
from .audit import L6AuditTraceEnvelope
from .envelope import L6PluginInvocationEnvelope, L6PluginOutputEnvelope
from .event_contract import L6EventContract, L6EventPayloadPolicy
from .events import L6PluginEventKind, VersionedPluginEventEnvelope
from .failure import (
    L6DegradationContract,
    L6FailureContract,
    L6FailureSeverity,
    L6HotSwitchReadinessContract,
    L6MigrationContract,
    L6RollbackContract,
)
from .forbidden_scan import (
    L6ForbiddenScanFinding,
    L6ForbiddenScanMatchMode,
    L6ForbiddenScanReport,
    L6ForbiddenScanRule,
    L6ForbiddenScanSeverity,
    default_l6_forbidden_scan_rules,
    scan_l6_text,
)
from .handoff import L6HandoffContract
from .handoff_phase2 import (
    AckEnvelope,
    AckNackEnvelopeContract,
    AggregationEnvelope,
    CancelEnvelope,
    FailureReturnEnvelope,
    FailureReturnEnvelopeContract,
    HandoffEnvelopeContract,
    L6HandoffKind,
    MessageEnvelopeContract,
    NackEnvelope,
    ResultReturnEnvelope,
    ResultReturnEnvelopeContract,
    TimeoutEnvelope,
    VersionedPluginHandoffEnvelope,
)
from .interoperation import (
    ActorCollaborationBoundaryContract,
    InteroperationBoundaryCheck,
    L6ForbiddenInteroperationMode,
    L6InteroperationMode,
    PluginInteroperationBoundaryContract,
)
from .invariants import L6InvariantCheckResult, L6InvariantRule, L6InvariantSeverity, L6InvariantSuite, default_l6_invariant_rules
from .invocation_return import L3PluginCandidateView, L6PluginDiscoverableProjection, L6PluginInvocationRequest, L6PluginOutputReturnEnvelope, L6PluginOutputStatus
from .lifecycle import (
    L6PluginLifecycleContract,
    L6PluginLifecycleDeclaration,
    L6PluginLifecycleState,
    is_declared_lifecycle_transition_allowed,
    lifecycle_declaration_digest,
)
from .manifest import L6PluginManifest, public_projection_from_manifest
from .phase2_quality import L6Phase2QualityGateDecision, L6Phase2RegressionMatrix, L6Phase2TestEvidenceIndex
from .projections_phase2 import (
    ActorCollaborationProjection,
    BeliefCandidateProjection,
    BeliefRequirement,
    ContextBeliefWorldHandoffEnvelope,
    ContextProjection,
    ContextRequirement,
    ContextSafetyProjection,
    ContextView,
    HandoffProjection,
    L6ProjectionKind,
    ResultAggregationProjection,
    VersionedStateProjectionEnvelope,
    WorldCandidateProjection,
    WorldRequirement,
)
from .public_projection import L6PublicProjection
from .quality_gate import L6QualityGateDecision
from .requirement import (
    ALLOWED_PROVIDER_NEUTRAL_HINTS,
    L6AuditRequirement,
    L6BudgetRequirement,
    L6CapabilityRequirement,
    L6CapabilityRequirementKind,
    L6ContextRequirement,
    L6CredentialRequirement,
    L6ModelCapabilityRequirement,
    L6PermissionRequirement,
    L6ToolCapabilityRequirement,
    L6ToolSideEffectGrade,
)
from .serialization import to_l6_digest, to_l6_json, to_l6_primitive
from .state_projection import L6StateProjectionContract, L6StateProjectionMode
from .versioning import (
    L6BreakingChangeAssessment,
    L6CompatibilityMatrix,
    L6ContractChangeKind,
    L6DeprecationPolicyDeclaration,
    L6EventSchemaVersionPolicy,
    L6HandoffSchemaVersionPolicy,
    L6HotSwitchReadinessDeclaration,
    L6LifecycleVersionPolicy,
    L6MigrationPlanDeclaration,
    L6ProjectionSchemaVersionPolicy,
    L6ReplayCompatibilityDeclaration,
    L6RollbackRouteDeclaration,
    L6VersionedContractRef,
    L6VersionedContractSet,
)

__all__ = (
    "ALLOWED_PROVIDER_NEUTRAL_HINTS",
    "AckEnvelope",
    "AckNackEnvelopeContract",
    "ActorCollaborationBoundaryContract",
    "ActorCollaborationProjection",
    "AggregationEnvelope",
    "BeliefCandidateProjection",
    "BeliefRequirement",
    "CancelEnvelope",
    "ContextBeliefWorldHandoffEnvelope",
    "ContextProjection",
    "ContextRequirement",
    "ContextSafetyProjection",
    "ContextView",
    "FailureReturnEnvelope",
    "FailureReturnEnvelopeContract",
    "HandoffEnvelopeContract",
    "HandoffProjection",
    "InteroperationBoundaryCheck",
    "L3PluginCandidateView",
    "L6AuditRequirement",
    "L6AuditTraceEnvelope",
    "L6BreakingChangeAssessment",
    "L6BudgetRequirement",
    "L6CapabilityRequirement",
    "L6CapabilityRequirementKind",
    "L6CompatibilityMatrix",
    "L6ContextRequirement",
    "L6ContractChangeKind",
    "L6ContractPatchAuditIndex",
    "L6ContractPatchPublicProjection",
    "L6ContractPatchQualityGateDecision",
    "L6CredentialRequirement",
    "L6DegradationContract",
    "L6DeprecationPolicyDeclaration",
    "L6EventContract",
    "L6EventPayloadPolicy",
    "L6EventSchemaVersionPolicy",
    "L6FailureContract",
    "L6FailureSeverity",
    "L6ForbiddenInteroperationMode",
    "L6ForbiddenScanFinding",
    "L6ForbiddenScanMatchMode",
    "L6ForbiddenScanReport",
    "L6ForbiddenScanRule",
    "L6ForbiddenScanSeverity",
    "L6HandoffContract",
    "L6HandoffKind",
    "L6HandoffSchemaVersionPolicy",
    "L6HotSwitchReadinessContract",
    "L6HotSwitchReadinessDeclaration",
    "L6InteroperationMode",
    "L6InvariantCheckResult",
    "L6InvariantRule",
    "L6InvariantSeverity",
    "L6InvariantSuite",
    "L6LifecycleVersionPolicy",
    "L6MigrationContract",
    "L6MigrationPlanDeclaration",
    "L6MiniSpecialtyDesignEnvelope",
    "L6ModelCapabilityRequirement",
    "L6PermissionRequirement",
    "L6Phase2QualityGateDecision",
    "L6Phase2RegressionMatrix",
    "L6Phase2TestEvidenceIndex",
    "L6PluginAdmissionDecision",
    "L6PluginAdmissionKind",
    "L6PluginAdmissionReport",
    "L6PluginDiscoverableProjection",
    "L6PluginEventKind",
    "L6PluginInvocationEnvelope",
    "L6PluginInvocationRequest",
    "L6PluginLifecycleContract",
    "L6PluginLifecycleDeclaration",
    "L6PluginLifecycleState",
    "L6PluginManifest",
    "L6PluginOutputEnvelope",
    "L6PluginOutputReturnEnvelope",
    "L6PluginOutputStatus",
    "L6ProjectionKind",
    "L6ProjectionSchemaVersionPolicy",
    "L6PublicContractPatchImpactAssessment",
    "L6PublicContractPatchProposal",
    "L6PublicProjection",
    "L6QualityGateDecision",
    "L6ReplayCompatibilityDeclaration",
    "L6RollbackContract",
    "L6RollbackRouteDeclaration",
    "L6StateProjectionContract",
    "L6StateProjectionMode",
    "L6ToolCapabilityRequirement",
    "L6ToolSideEffectGrade",
    "L6VersionedContractRef",
    "L6VersionedContractSet",
    "MessageEnvelopeContract",
    "NackEnvelope",
    "PluginInteroperationBoundaryContract",
    "ResultAggregationProjection",
    "ResultReturnEnvelope",
    "ResultReturnEnvelopeContract",
    "TimeoutEnvelope",
    "VersionedPluginEventEnvelope",
    "VersionedPluginHandoffEnvelope",
    "VersionedStateProjectionEnvelope",
    "WorldCandidateProjection",
    "WorldRequirement",
    "default_l6_forbidden_scan_rules",
    "default_l6_invariant_rules",
    "is_declared_lifecycle_transition_allowed",
    "lifecycle_declaration_digest",
    "public_projection_from_manifest",
    "scan_l6_text",
    "to_l6_digest",
    "to_l6_json",
    "to_l6_primitive",
)
