from __future__ import annotations

L6_PHASE7_INVARIANTS: tuple[str, ...] = (
    "adaptive_collaboration_plugin_is_not_executor",
    "learning_need_review_is_not_learning_execution",
    "skill_candidate_is_not_registered_skill",
    "skill_patch_candidate_is_not_skill_write",
    "tool_gap_requirement_is_not_tool_production",
    "self_healing_diagnosis_is_not_healing_execution",
    "repair_plan_candidate_is_not_code_patch",
    "file_patch_requirement_is_not_file_write",
    "test_run_requirement_is_not_test_execution",
    "regression_requirement_is_not_pytest_execution",
    "iteration_proposal_is_not_iteration_apply",
    "contract_patch_candidate_is_not_contract_patch",
    "evolution_candidate_review_is_not_evolution_execution",
    "collaboration_plan_candidate_is_not_plugin_dispatch",
    "handoff_aggregation_is_not_auto_merge",
    "conflict_resolution_suggestion_is_not_decision",
    "long_chain_recovery_plan_is_not_scheduler_state",
    "no_live_model_call",
    "no_raw_tool_call",
    "no_direct_l4_adapter_call",
    "no_direct_file_write",
    "no_direct_test_execution",
    "no_direct_l2_write",
    "no_direct_memory_write",
    "no_direct_memory_delete",
    "no_direct_audit_write",
    "no_direct_budget_charge",
    "no_raw_secret",
    "no_provider_base_url_or_api_key",
    "no_plugin_direct_import_call_state_write",
    "no_parallel_runtime",
    "no_parallel_agent_scheduler",
    "no_old_runtime_or_abilitypackage_backflow",
    "public_projection_minimal_disclosure",
    "adaptive_learning_should_continue_when_low_risk",
    "adaptive_failure_should_recover_not_abort",
    "adaptive_repair_candidate_should_not_patch",
    "adaptive_collaboration_should_not_direct_call",
    "adaptive_conflict_suggestion_should_not_decide",
    "adaptive_handoff_aggregation_should_not_merge",
    "adaptive_iteration_candidate_should_not_apply",
    "adaptive_evolution_candidate_should_not_execute",
    "adaptive_result_must_not_be_faked",
)

def has_invariant(name: str) -> bool:
    return name in L6_PHASE7_INVARIANTS
